mode: Mainline
commit-message-incrementing: Enabled
commit-message-strategy: Patch
commit-message-incrementing-strategies:
  Patch:
    - '^fix\\:'
    - '^chore\\:'
    - '^docs\\:'
    - "^added"
    - ".*"
  Minor:
    - '^feat\\:'
  Major:
    - '^feat\\!'
    - "^BREAKING CHANGE"
